# Generated by Django 4.2.7 on 2025-03-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_language_switcher', models.BooleanField(default=False)),
                ('secondary_language', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(related_name='microsites', to='management.branch')),
            ],
        ),
        migrations.CreateModel(
            name='MicrositeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('menu', 'Menu'), ('testimonials', 'Testimonials'), ('location', 'Location'), ('contact', 'Contact'), ('about', 'About')], max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('microsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='microsites.microsite')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('microsite', 'section_type')},
            },
        ),
    ]
