# Generated by Django 4.2.7 on 2025-03-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('microsites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsite',
            name='has_language_switcher',
        ),
        migrations.RemoveField(
            model_name='microsite',
            name='secondary_language',
        ),
        migrations.RemoveField(
            model_name='microsite',
            name='slug',
        ),
        migrations.AddField(
            model_name='microsite',
            name='site_id',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='microsite',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='microsites', to='management.branch'),
        ),
        migrations.AlterField(
            model_name='microsite',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
