# Generated by Django 4.2.7 on 2025-03-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microsites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('microsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='microsites.microsite')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('microsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='microsites.microsite')),
            ],
        ),
        migrations.CreateModel(
            name='FoodDeliveryEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('microsite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_delivery_embed', to='microsites.microsite')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('external_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('microsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='microsites.microsite')),
            ],
        ),
    ]
