# Generated by Django 4.2.7 on 2025-03-24 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microsites', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='external_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='career',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddeliveryembed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddeliveryembed',
            name='name',
            field=models.CharField(default='Food Delivery Service', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddeliveryembed',
            name='url',
            field=models.URLField(default='default url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooddeliveryembed',
            name='microsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_delivery_embeds', to='microsites.microsite'),
        ),
    ]
