# Generated by Django 4.2.7 on 2025-03-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsites', '0001_initial'),
        ('content', '0002_rename_title_career_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='microsite',
        ),
        migrations.RemoveField(
            model_name='fooddeliveryembed',
            name='embed_code',
        ),
        migrations.RemoveField(
            model_name='fooddeliveryembed',
            name='microsite',
        ),
        migrations.AddField(
            model_name='career',
            name='microsites',
            field=models.ManyToManyField(related_name='careers', to='microsites.microsite'),
        ),
        migrations.AddField(
            model_name='fooddeliveryembed',
            name='microsites',
            field=models.ManyToManyField(related_name='food_delivery_embeds', to='microsites.microsite'),
        ),
        migrations.AlterField(
            model_name='career',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddeliveryembed',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
