# Generated by Django 4.2.7 on 2025-03-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsites', '0001_initial'),
        ('content', '0003_remove_career_microsite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='microsite',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('AED', 'UAE Dirham')], default='USD', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='microsites',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='microsites.microsite'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
