# Generated by Django 4.2.7 on 2025-03-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsites', '0002_remove_microsite_has_language_switcher_and_more'),
        ('content', '0004_remove_menuitem_microsite_menuitem_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='microsite',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='microsites',
            field=models.ManyToManyField(blank=True, related_name='testimonials', to='microsites.microsite'),
        ),
    ]
