# Generated by Django 4.2.7 on 2025-03-25 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('microsites', '0002_remove_microsite_has_language_switcher_and_more'),
        ('content', '0005_remove_testimonial_microsite_testimonial_microsites'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers', to='management.branch'),
        ),
        migrations.AddField(
            model_name='career',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='management.branch'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, '0 Stars'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='microsites',
            field=models.ManyToManyField(blank=True, related_name='careers', to='microsites.microsite'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
