# Generated by Django 4.2.7 on 2025-03-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_career_branch_career_department_career_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
