# Generated by Django 4.2.7 on 2025-03-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.TextField(max_length=160)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Base SEO Configuration',
                'verbose_name_plural': 'Base SEO Configuration',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_links', to='management.branch')),
            ],
        ),
    ]
